---

- include: facts.yml
- include: user.yml
- include: directories.yml
- include: install.yml
- include: conf.yml
- include: iptables.yml
  when: iptables_manage | default(True)
- include: service.yml
- include: write_version.yml
