---

- name: Create directory structure
  file: path={{ riot_root_dir }}/{{ item.dir }} state=directory owner={{ item.owner | default(omit) }} group={{ item.group | default(omit) }} mode={{ item.mode | default(omit) }}
  with_items:
    - dir: tmp
    - dir: archives
      mode: 700
    - dir: meta
      mode: 700
  tags: matrix
