---

  # Here we use a template instead of yum_repository because
  # we might need to set module_hotfixes = true for el8. And yum_repository
  # doesn't support this setting
- name: Configure Postgres repo
  template: src=postgresql.repo.j2 dest=/etc/yum.repos.d/postgresql.repo
  tags: pg,repo
