---

- name: Compress previous version
  command: tar cf {{ appsmith_root_dir }}/archives/{{ appsmith_current_version }}.tar.zst --use-compress-program=zstd ./
  environment:
    ZST_CLEVEL: 10
  args:
    chdir: "{{ appsmith_root_dir }}/archives/{{ appsmith_current_version }}"
    warn: False
  tags: appsmith
