---

- include: facts.yml
- include: directories.yml
- include: archive_pre.yml
  when: element_install_mode == 'upgrade'
- include: install.yml
- include: conf.yml
- include: archive_post.yml
  when: element_install_mode == 'upgrade'
- include: write_version.yml
- include: cleanup.yml

