---

- include: ../common/handlers/main.yml

- name: restart ksmtuned
  service: name=ksmtuned state=restarted

- name: restart o2cb
  service: name=o2cb state=restarted
  when: pve_ocfs2 == True

- name: restart pveproxy
  service: name=pveproxy state=restarted

- name: restart pvedaemon
  service: name=pvedaemon state=restarted

- name: restart pve-ha-lrm
  service: name=pve-ha-lrm state=restarted
