---

- import_tasks: ../includes/webapps_compress_archive.yml
  vars:
    - root_dir: "{{ itop_root_dir }}"
    - version: "{{ itop_current_version }}"
  when: itop_install_mode == 'upgrade'
  tags: itop

