---

docker_local_persist_version: 1.3.0
docker_local_persist_url: https://github.com/MatchbookLab/local-persist/releases/download/v{{ docker_local_persist_version }}/local-persist-linux-amd64
docker_local_persist_sha1: 41a2169525575da40695451f95cfc5f2c314ab6d

