---

- include: user.yml
- include: directories.yml
- include: facts.yml
- include: archive_pre.yml
  when: glpi_install_mode == 'upgrade'
- include: install.yml
- include: conf.yml
- include: cleanup.yml
- include: write_version.yml
- include: archive_post.yml
  when: glpi_install_mode == 'upgrade'
- include: filebeat.yml
