---

- name: Create directories
  file: path={{ etherpad_root_dir }}/{{ item.dir }} state=directory owner={{ item.owner | default(omit) }} group={{ item.group | default(omit) }} mode={{ item.mode | default(omit) }}
  loop:
    - dir: meta
      mode: 700
    - dir: tmp
      mode: 770
      group: "{{ etherpad_user }}"
    - dir: backup
      mode: 700
    - dir: archives
      mode: 700
    - dir: app
      owner: "{{ etherpad_user }}"
  tags: etherpad

