---

- name: Add PBS repo key
  apt_key:
    url: https://enterprise.proxmox.com/debian/proxmox-{{ ansible_distribution_major_version is version('11', '>=') | ternary('release-' ~ ansible_distribution_release, 've-release-6.x.gpg') }}.gpg
  environment:
    https_proxy: "{{ system_proxy | default('') }}"
  tags: repo

- name: Add PBS repo
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pbs {{ ansible_distribution_release }} pbs-no-subscription
    filename: pbs
  tags: repo

