---

- include_vars: "{{ item }}"
  with_first_found:
    - vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml
    - vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml
    - vars/{{ ansible_distribution }}.yml
    - vars/{{ ansible_os_family }}.yml

- include: facts.yml
- include_tasks: utils.yml
- include_tasks: hostname.yml
- include_tasks: tz.yml
- include_tasks: tuned.yml
  when:
    - ansible_virtualization_role == 'host' or ansible_virtualization_type != 'lxc'
    - ansible_os_family == 'RedHat'
- include_tasks: mail.yml
- include_tasks: system.yml
- include_tasks: hardware.yml
  when: ansible_virtualization_role == 'host'
- include_tasks: guest.yml
  when:
    - ansible_virtualization_role == 'guest'

...
