---

- name: Handle papermerge port in the firewall
  iptables_raw:
    name: papermerge_port
    state: "{{ (papermerge_src_ip | length > 0) | ternary('present','absent') }}"
    rules: "-A INPUT -m state --state NEW -p tcp -m multiport --dports {{ papermerge_port }},{{ papermerge_port | int + 1 }} -s {{ papermerge_src_ip | join(',') }} -j ACCEPT"
  tags: firewall,ged

