---

- include: user.yml
- include: directories.yml
- include: facts.yml
- include: archive_pre.yml
  when: papermerge_install_mode == 'upgrade'
- include: install.yml
- include: selinux.yml
  when: ansible_selinux.status == 'enabled'
- include: conf.yml
- include: iptables.yml
  when: iptables_manage | default(True)
- include: services.yml
- include: write_version.yml
- include: archive_post.yml
  when: papermerge_install_mode == 'upgrade'
- include: cleanup.yml
