---

- name: Install tomcat
  yum:
    name:
      - tomcat
  tags: diagrams

- include: directories.yml
- include: facts.yml
- include: archive_pre.yml
  when: diagrams_install_mode == 'upgrade'
- include: install.yml
- include: conf.yml
- include: selinux.yml
  when: ansible_selinux.status == 'enabled'
- include: iptables.yml
  when: iptables_manage | default(True)
- include: services.yml
- include: write_version.yml
- include: archive_post.yml
  when: diagrams_install_mode == 'upgrade'
- include: cleanup.yml
